# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_desc', models.TextField()),
                ('task_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
