# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=20, null=True)),
                ('notice_desc', models.TextField()),
                ('notice_author', models.CharField(max_length=20)),
                ('notice_valid_till', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('notice_publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
