# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_api_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='choices',
            field=models.CharField(choices=[('Official', 'Official'), ('Branch', 'Branch'), ('All', 'All')], default='All', max_length=1, null=True),
        ),
    ]
