# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171105_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('BCE', 'BCE'), ('ME', 'ME'), ('ECE', 'ECE'), ('EE', 'EE'), ('CE', 'CE'), ('CHE', 'CHE')], default='None', max_length=20, null=True),
        ),
    ]
